pipeline {
    agent any

    environment {
        MAVEN_HOME = '/usr/share/maven'
        PATH = "$MAVEN_HOME/bin:$PATH"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                // Build and test the Maven project
                sh 'mvn clean test'
            }
        }

        stage('Build Docker Image') {
            steps {
                // Build the Docker image using the Dockerfile in the project
                script {
                    dockerImage = docker.build("test-jenkins:${env.BUILD_NUMBER}")
                }
            }
        }
    }

    post {
        success {
            // Archive test results in JUnit XML format
            junit '**/target/surefire-reports/*.xml'

            // Save test results to a file
            script {
                def junitResults = junit testResults: '**/target/surefire-reports/*.xml', allowEmptyResults: true
                junitResults.writeTo("junit-results.xml")
            }

            // Perform actions when the build is successful
            echo 'Build and Docker image creation successful!'
        }
        failure {
            // Perform actions when the build fails
            echo 'Build failed!'
        }
        always {
            // Cleanup or additional steps to perform after the main stages
            script {
                echo 'Pipeline completed!'
            }
        }
    }
}
